"use client"
import { useEffect } from "react"
import { X, ChevronRight } from "lucide-react"
import { clearDocumentScrollLock } from "@/lib/clear-scroll-lock"
import styles from "./quick-menu.module.css"
export function QuickMenuSheet({ open, onOpenChange, onSelectTrip, onSelectExpense, onSelectPlace }: { open: boolean; onOpenChange: (open: boolean) => void; onSelectTrip: () => void; onSelectExpense: () => void; onSelectPlace: () => void }) {
 useEffect(() => { if (!open) return; const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onOpenChange(false) }; window.addEventListener("keydown", onKey); document.body.style.overflow = "hidden"; return () => { window.removeEventListener("keydown", onKey); clearDocumentScrollLock() } }, [open, onOpenChange])
 return <div className={`fixed inset-0 z-50 ${open ? "" : "pointer-events-none"}`} aria-hidden={!open} inert={!open}><button aria-label="닫기" className={`absolute inset-0 bg-black/30 transition-opacity duration-300 ${open ? "opacity-100" : "opacity-0"}`} onClick={() => onOpenChange(false)} /><div role="dialog" aria-modal="true" aria-label="무엇을 추가할까요?" className={`absolute inset-x-0 bottom-0 mx-auto max-w-md rounded-t-[28px] bg-white px-6 pt-4 pb-[max(28px,env(safe-area-inset-bottom))] transition-transform duration-300 ease-out motion-reduce:transition-none ${open ? "translate-y-0" : "translate-y-full"}`}><div className="mb-4 flex min-h-11 items-center justify-between"><h2 className="text-[21px] font-semibold">무엇을 추가할까요?</h2><button onClick={() => onOpenChange(false)} className="p-2" aria-label="닫기"><X size={24}/></button></div><div className="space-y-4">{([
 ["trip","새 여행 만들기","함께 떠날 여행을 시작해요",onSelectTrip], ["expense","지출 추가","쓴 금액을 여행 정산에 기록해요",onSelectExpense], ["place","장소 추가","가고 싶은 곳을 여행에 저장해요",onSelectPlace],
 ] as const).map(([key,title,desc,action],i) => <button key={key} onClick={action} className={`flex min-h-[62px] w-full items-center gap-4 text-left active:opacity-60 ${open ? styles.row : ""}`} style={{ animationDelay: `${100+i*80}ms` }}>{key === "trip" ? <span className={`relative block size-11 shrink-0 ${open ? styles.suitcase : ""}`}><img src="/design/quick-add-background.svg" width="44" height="44" alt=""/><img src="/design/quick-add-case.svg" alt="" className={styles.case} /><span className={styles.badge}><img src="/design/quick-add-badge.svg" width="18" height="18" alt=""/><img src="/design/quick-add-plus.svg" width="8" height="8" alt="" className="absolute left-[5px] top-[5px]"/></span></span> : <img src={`/design/quick-add-${key}.svg`} width="44" height="44" alt=""/>}<span className="flex-1"><span className="block text-[17px] font-semibold">{title}</span><span className="mt-1 block text-xs text-slate-500">{desc}</span></span><ChevronRight size={20} className="text-slate-500"/></button>)}</div></div></div>
}
